source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-asset-pipeline"

gem "uglifier"
gem "haml"

gem "sprockets-babel"

source "https://rails-assets.org" do
  gem "rails-assets-jquery"
  gem "rails-assets-bootstrap"
end
